# Generated by Django 4.0.5 on 2022-07-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_comment_likes_comment_sub_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_profile_picture.jpeg', null=True, upload_to='profile_pictures'),
        ),
    ]
